services:
  pocket-tts:
    image: halfnothing/pocket-tts:latest
    container_name: pocket-tts
    ports:
      - "8000:8000"
    environment:
      - HTT
    volumes:
      - ./cache:/root/.cache/huggingface
    networks:
      - main

networks:
  main:
    external: true